---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/username/public_html/NSGH

    # Install Python dependencies in cPanel virtual environment
    - /usr/local/bin/pip install -r api/requirements.txt

    # Copy all frontend files (recursively) to deployment path
    - /bin/cp -R !(api|.git|venv) $DEPLOYPATH/

    # Copy API folder
    - /bin/cp -R api $DEPLOYPATH/

    # Remove .git folder if accidentally copied
    - /bin/rm -rf $DEPLOYPATH/api/.git