---
deployment:
  tasks:
    - /bin/cp -R css /home/nsghbdco/public_html/
    - /bin/cp -R dashboard /home/nsghbdco/public_html/
    - /bin/cp -R fontawesome /home/nsghbdco/public_html/
    - /bin/cp -R fonts /home/nsghbdco/public_html/
    - /bin/cp -R img /home/nsghbdco/public_html/
    - /bin/cp -R js /home/nsghbdco/public_html/
    - /bin/cp *.html /home/nsghbdco/public_html/
    - /bin/cp data.json /home/nsghbdco/public_html/
