---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nsghbdco/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R dashboard $DEPLOYPATH
    - /bin/cp -R fontawesome $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
