const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await page.addInitScript(() => { window.NSGH_API_BASE = 'http://127.0.0.1:8765'; });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept());
  await page.request.post('http://127.0.0.1:8765/__test/reset');
  const login = async (phone) => {
    await page.goto('http://127.0.0.1:8765/appointment.html');
    await page.fill('#login-phone', phone);
    await page.fill('#login-password', 'secret123');
    await page.locator('#login-form button[type=submit]').click();
  };
  await login('01712345678');
  await page.locator('#commission-sms-panel-view').waitFor({ state: 'visible' });
  await page.waitForFunction(() => commissionState.loaded);
  assert.equal(await page.locator('#sidebar-nav').innerText(), 'COMMISSION SMS\nSend SMS\nDoctors\nSMS Templates\nSMS History');
  assert.equal(await page.inputValue('#commission-date'), await page.evaluate(() => commissionToday()));
  await page.locator('#tab-commission-doctors').click();
  await page.getByRole('button', {name: '+ Add doctor', exact: true}).click();
  await page.fill('#commission-edit-doctor_id', 'DR-101');
  await page.fill('#commission-edit-name', 'Dr. Amina Rahman');
  await page.fill('#commission-edit-address', 'Shafipur, Gazipur');
  await page.fill('#commission-edit-phone', '01712345671');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  assert.match(await page.locator('#commission-doctor-list').innerText(), /Dr. Amina Rahman/);
  await page.locator('#commission-doctor-list').getByRole('button', {name: 'Edit', exact: true}).click();
  await page.fill('#commission-edit-address', 'Shafipur, Gazipur, Bangladesh');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  await page.locator('#tab-commission-templates').click();
  await page.getByRole('button', { name: 'Edit template', exact: true }).click();
  await page.fill('#commission-edit-body', 'Dear {name}, your commission payment of BDT {amount} for {date} has been sent. Thank you for your partnership.');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  await page.evaluate(() => commissionRequest('/doctors', { method: 'POST', body: JSON.stringify({ doctor_id: 'DR-102', name: 'Dr. Karim Ahmed', address: 'Dhaka', phone: '01712345673' }) }));
  await page.locator('#tab-commission-send').click();
  await page.waitForFunction(() => commissionState.loaded);
  const search = page.locator('#commission-recipient-search');
  const suggestions = page.locator('#commission-doctor-suggestions');
  const results = page.locator('#commission-doctor-search-results');
  await search.focus();
  assert.equal(await results.isVisible(), false, 'Empty search must not show suggestions');
  for (const query of [' dr-101 ', 'AMINA', '01712345671', 'gazipur']) {
    await search.fill(query);
    assert.equal(await suggestions.getByRole('option').count(), 1);
    assert.match(await suggestions.innerText(), /Dr. Amina Rahman · DR-101\n01712345671\nShafipur, Gazipur, Bangladesh/);
  }
  await suggestions.getByRole('option').click();
  assert.equal(await results.isVisible(), false);
  assert.equal(await page.locator('#commission-doctor-select option:checked').textContent(), 'DR-101 · Dr. Amina Rahman');
  assert.match(await page.locator('#commission-doctor-detail').innerText(), /Amina/);
  assert.match(await page.locator('#commission-preview').innerText(), /Dear Dr. Amina Rahman/);
  await search.fill('no matching doctor');
  assert.equal(await page.inputValue('#commission-doctor-select'), '');
  assert.equal(await suggestions.getByRole('option').count(), 0);
  assert.equal(await page.locator('#commission-doctor-search-empty').isVisible(), true);
  assert.equal(await page.locator('#commission-send-button').isDisabled(), true);
  await search.fill('dr-10');
  assert.equal(await suggestions.getByRole('option').count(), 2);
  await search.press('ArrowDown');
  const firstActive = await search.getAttribute('aria-activedescendant');
  await search.press('ArrowDown');
  const secondActive = await search.getAttribute('aria-activedescendant');
  assert.notEqual(firstActive, secondActive);
  await search.press('ArrowUp');
  assert.equal(await search.getAttribute('aria-activedescendant'), firstActive);
  await search.press('ArrowDown');
  const keyboardDoctor = await page.locator(`#${secondActive}`).getAttribute('data-doctor-id');
  await search.press('Enter');
  assert.equal(await page.inputValue('#commission-doctor-select'), keyboardDoctor);
  assert.equal(await search.getAttribute('aria-expanded'), 'false');
  assert.equal(await search.getAttribute('aria-activedescendant'), null);
  await search.press('ArrowUp');
  assert.equal(await results.isVisible(), true);
  await search.press('Escape');
  assert.equal(await results.isVisible(), false);
  await search.fill('amina');
  await search.press('Tab');
  assert.equal(await results.isVisible(), false, 'Leaving the search must close suggestions');
  await search.fill('');
  assert.equal(await results.isVisible(), false);
  assert.equal(await page.locator('#commission-doctor-select option').count(), 3);
  await page.selectOption('#commission-doctor-select', {label: 'DR-101 · Dr. Amina Rahman'});
  await page.fill('#commission-amount', '3500.50');
  await search.fill('amina');
  await search.press('ArrowDown');
  await search.press('Enter');
  await search.press('Enter');
  assert.equal(await page.evaluate(async () => (await commissionRequest('/history')).total), 0, 'Search Enter must not send SMS');
  await search.fill('dr-10');
  await page.screenshot({ path: '.cache/commission-suggestions-desktop.png', fullPage: true });
  await search.press('Escape');
  assert.match(await page.locator('#commission-preview').innerText(), /Dear Dr. Amina Rahman.*BDT 3500.50/);
  await page.screenshot({ path: '.cache/commission-desktop.png', fullPage: true });
  await page.locator('#commission-send-button').click();
  await page.waitForFunction(() => document.getElementById('commission-send-result').textContent.includes('submitted'));
  await page.locator('#tab-commission-history').click();
  await page.waitForFunction(() => document.getElementById('commission-history-count').textContent.includes('1 of 1'));
  await page.locator('#commission-history-list summary').click();
  assert.match(await page.locator('#commission-history-list').innerText(), /BDT 3500.50/);
  await page.reload();
  await page.locator('#commission-history-content').waitFor({state: 'visible'});
  await page.waitForFunction(() => document.getElementById('commission-history-count').textContent.includes('1 of 1'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForFunction(() => parseFloat(getComputedStyle(document.getElementById('main-content')).marginLeft) === 0);
  await page.screenshot({ path: '.cache/commission-mobile-history.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile page overflows horizontally');
  await page.evaluate(() => switchCommissionTab('commission-send'));
  await page.waitForFunction(() => commissionState.loaded);
  await search.fill('gazipur');
  await page.screenshot({ path: '.cache/commission-suggestions-mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await suggestions.getByRole('option').click();
  assert.equal(await results.isVisible(), false);
  await page.selectOption('#commission-doctor-select', {label: 'DR-101 · Dr. Amina Rahman'});
  await page.fill('#commission-amount', '1200');
  await page.screenshot({ path: '.cache/commission-mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  // Simulate a connection dropping AFTER the server submitted the SMS.
  let lostResponse = true;
  await page.route('**/commission-sms/send', async route => {
    if (lostResponse) {
      lostResponse = false;
      await route.fetch();
      await route.abort('failed');
    } else await route.continue();
  });
  await page.locator('#commission-send-button').click();
  await page.waitForFunction(() => document.getElementById('commission-send-result').textContent.includes('Retry with the same details'));
  await page.locator('#commission-send-button').click();
  await page.waitForFunction(() => document.getElementById('commission-send-result').textContent.includes('submitted'));
  assert.equal(await page.evaluate(async () => (await commissionRequest('/history')).total), 2);
  await page.evaluate(() => logout());
  assert.equal(await page.locator('#commission-doctor-list').textContent(), '');
  assert.equal(await page.locator('#commission-history-list').textContent(), '');
  assert.equal(await search.inputValue(), '');
  assert.equal(await suggestions.textContent(), '');
  assert.equal(await search.getAttribute('aria-expanded'), 'false');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await login('admin');
  await page.locator('#admin-view').waitFor({ state: 'visible' });
  await page.locator('#tab-admin-commission-sms-users').click();
  assert.match(await page.locator('#commission-user-list').innerText(), /Commission Operator/);
  await page.getByRole('button', {name: '+ Add user', exact: true}).click();
  await page.fill('#commission-edit-name', 'Second Operator');
  await page.fill('#commission-edit-phone', '01712345672');
  await page.fill('#commission-edit-password', 'secret123');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  const row = page.locator('#commission-user-list tr').filter({ hasText: 'Second Operator' });
  await row.getByRole('button', {name:'Edit', exact:true}).click();
  await page.fill('#commission-edit-name', 'Updated Operator');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({state:'hidden'});
  await page.locator('#commission-user-list tr').filter({hasText:'Updated Operator'}).getByRole('button',{name:'Delete',exact:true}).click();
  await page.waitForFunction(() => !document.getElementById('commission-user-list').textContent.includes('Updated Operator'));
  await page.screenshot({path:'.cache/commission-admin.png', fullPage:true});
  assert.deepEqual(errors, []);
  console.log('PASS: doctor suggestions, matching, mouse/keyboard selection, dismissal, Enter safety, login, role navigation, doctor CRUD, template editing, SMS preview/send/history, network retry, reload restoration, mobile layout, logout cleanup, admin account CRUD; no browser errors.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
