const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await page.addInitScript(() => { window.NSGH_API_BASE = 'http://127.0.0.1:8765'; });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept());
  await page.request.post('http://127.0.0.1:8765/__test/reset');
  const login = async (phone) => {
    await page.goto('http://127.0.0.1:8765/appointment.html');
    await page.fill('#login-phone', phone);
    await page.fill('#login-password', 'secret123');
    await page.locator('#login-form button[type=submit]').click();
  };
  await login('01712345678');
  await page.locator('#commission-sms-panel-view').waitFor({ state: 'visible' });
  await page.waitForFunction(() => commissionState.loaded);
  assert.equal(await page.locator('#sidebar-nav').innerText(), 'COMMISSION SMS\nSend SMS\nDoctors\nSMS Templates\nSMS History');
  assert.equal(await page.inputValue('#commission-date'), await page.evaluate(() => commissionToday()));
  await page.locator('#tab-commission-doctors').click();
  await page.getByRole('button', {name: '+ Add doctor', exact: true}).click();
  await page.fill('#commission-edit-doctor_id', 'DR-101');
  await page.fill('#commission-edit-name', 'Dr. Amina Rahman');
  await page.fill('#commission-edit-address', 'Shafipur, Gazipur');
  await page.fill('#commission-edit-phone', '01712345671');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  assert.match(await page.locator('#commission-doctor-list').innerText(), /Dr. Amina Rahman/);
  await page.locator('#commission-doctor-list').getByRole('button', {name: 'Edit', exact: true}).click();
  await page.fill('#commission-edit-address', 'Shafipur, Gazipur, Bangladesh');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  await page.locator('#tab-commission-templates').click();
  await page.getByRole('button', { name: 'Edit template', exact: true }).click();
  await page.fill('#commission-edit-body', 'Dear {name}, your commission payment of BDT {amount} for {date} has been sent. Thank you for your partnership.');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  await page.locator('#tab-commission-send').click();
  await page.waitForFunction(() => commissionState.loaded);
  await page.selectOption('#commission-doctor-select', {label: 'DR-101 · Dr. Amina Rahman'});
  await page.fill('#commission-amount', '3500.50');
  assert.match(await page.locator('#commission-preview').innerText(), /Dear Dr. Amina Rahman.*BDT 3500.50/);
  await page.screenshot({ path: '.cache/commission-desktop.png', fullPage: true });
  await page.locator('#commission-send-button').click();
  await page.waitForFunction(() => document.getElementById('commission-send-result').textContent.includes('submitted'));
  await page.locator('#tab-commission-history').click();
  await page.waitForFunction(() => document.getElementById('commission-history-count').textContent.includes('1 of 1'));
  await page.locator('#commission-history-list summary').click();
  assert.match(await page.locator('#commission-history-list').innerText(), /BDT 3500.50/);
  await page.reload();
  await page.locator('#commission-history-content').waitFor({state: 'visible'});
  await page.waitForFunction(() => document.getElementById('commission-history-count').textContent.includes('1 of 1'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForFunction(() => parseFloat(getComputedStyle(document.getElementById('main-content')).marginLeft) === 0);
  await page.screenshot({ path: '.cache/commission-mobile-history.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile page overflows horizontally');
  await page.evaluate(() => switchCommissionTab('commission-send'));
  await page.waitForFunction(() => commissionState.loaded);
  await page.selectOption('#commission-doctor-select', {label: 'DR-101 · Dr. Amina Rahman'});
  await page.fill('#commission-amount', '1200');
  await page.screenshot({ path: '.cache/commission-mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  // Simulate a connection dropping AFTER the server submitted the SMS.
  let lostResponse = true;
  await page.route('**/commission-sms/send', async route => {
    if (lostResponse) {
      lostResponse = false;
      await route.fetch();
      await route.abort('failed');
    } else await route.continue();
  });
  await page.locator('#commission-send-button').click();
  await page.waitForFunction(() => document.getElementById('commission-send-result').textContent.includes('Retry with the same details'));
  await page.locator('#commission-send-button').click();
  await page.waitForFunction(() => document.getElementById('commission-send-result').textContent.includes('submitted'));
  assert.equal(await page.evaluate(async () => (await commissionRequest('/history')).total), 2);
  await page.evaluate(() => logout());
  assert.equal(await page.locator('#commission-doctor-list').textContent(), '');
  assert.equal(await page.locator('#commission-history-list').textContent(), '');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await login('admin');
  await page.locator('#admin-view').waitFor({ state: 'visible' });
  await page.locator('#tab-admin-commission-sms-users').click();
  assert.match(await page.locator('#commission-user-list').innerText(), /Commission Operator/);
  await page.getByRole('button', {name: '+ Add user', exact: true}).click();
  await page.fill('#commission-edit-name', 'Second Operator');
  await page.fill('#commission-edit-phone', '01712345672');
  await page.fill('#commission-edit-password', 'secret123');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({ state: 'hidden' });
  const row = page.locator('#commission-user-list tr').filter({ hasText: 'Second Operator' });
  await row.getByRole('button', {name:'Edit', exact:true}).click();
  await page.fill('#commission-edit-name', 'Updated Operator');
  await page.locator('#commission-editor-save').click();
  await page.locator('#commission-editor').waitFor({state:'hidden'});
  await page.locator('#commission-user-list tr').filter({hasText:'Updated Operator'}).getByRole('button',{name:'Delete',exact:true}).click();
  await page.waitForFunction(() => !document.getElementById('commission-user-list').textContent.includes('Updated Operator'));
  await page.screenshot({path:'.cache/commission-admin.png', fullPage:true});
  assert.deepEqual(errors, []);
  console.log('PASS: login, role navigation, doctor CRUD, template editing, SMS preview/send/history, network retry, reload restoration, mobile layout, logout cleanup, admin account CRUD; no browser errors.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
